import React from "react";

export default function Head() {
  return (
    <div>
      <title>About page</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by Mohan" />
      <link rel="icon" href="/favicon.ico" />
    </div>
  );
}
